import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "SecureSteps - Crime Mapping Application",
  description:
    "Interactive crime mapping platform providing real-time visualization of local security incidents to enhance community safety awareness",
  keywords: [
    "crime map",
    "safety",
    "community",
    "security",
    "crime data",
    "public safety",
  ],
  authors: [{ name: "SecureSteps Team" }],
  viewport: "width=device-width, initial-scale=1",
  robots: "index, follow",
>>>>>>> 787c84d8ee403fd8fdf28995c8bb80d3340e8097
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
